//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaspisKusach
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RouteScheduleDataBaseEntities : DbContext
    {
        public RouteScheduleDataBaseEntities()
            : base("name=RouteScheduleDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carriages> Carriages { get; set; }
        public virtual DbSet<Routes> Routes { get; set; }
        public virtual DbSet<RoutesStations> RoutesStations { get; set; }
        public virtual DbSet<Station> Station { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
        public virtual DbSet<Trains> Trains { get; set; }
        public virtual DbSet<Trips> Trips { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
