//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaspisKusach
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoutesStations
    {
        public int IdRouteStation { get; set; }
        public int IdRoute { get; set; }
        public int IdStation { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual Routes Routes { get; set; }
        public virtual Station Station { get; set; }
    }
}
