//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaspisKusach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int IdRoute { get; set; }
        public int IdTrain { get; set; }
        public string Departure { get; set; }
        public string Arrival { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public System.DateTime ArrivalDate { get; set; }
    }
}
